#
#   TU Eindhoven
#   Eindhoven, The Netherlands
#
#   Author          :   Sander Stuijk (sander@ics.ele.tue.nl)
#
#   Date            :   March 29, 2002
#   

include $(SDF3ROOT)/etc/Makefile.inc

#-------------------------------------------------------------------------------
# Variables
#-------------------------------------------------------------------------------

COMPONENTS      = buffer_throughput dot hapi html schedule xml
TOOLS           = 
MODULE_SH_LIB   = 

#-------------------------------------------------------------------------------
# Rules
#-------------------------------------------------------------------------------

include $(SDF3ROOT)/etc/Makefile-modules.rules

#-------------------------------------------------------------------------------
# Additional rules
#-------------------------------------------------------------------------------
